lime-conure/bookworms

- server/db/models/author/author.js
- server/db/models/club/club.js
- server/db/models/message/message.js
- server/db/models/user/user.js
> feat: add user, author, message, club models

- server/db/models/book/book.js
- server/db/models/media/media.js
- server/db/models/thread/thread.js
created models:
book, thread, media models
> feat- book, thread, media models

- server/db/models/club/club.js
> fix: typo in club model

- script/seed.js
- server/api/clubs.js
- server/db/models/poll/poll.js
- makes sure clubId in api route is equal to clubId of poll you're voting on
> feat: securing voting api route

- server/api/clubs.js
- server/db/models/poll/poll.js
> feat: added get /polls route

- server/api/clubs.js
- server/db/models/poll/poll.js
> feat: added post /polls

- client/routes.js
> fix: polls-component

- server/api/books.js
- server/api/index.js
> feat: GET /book route added

- client/Components/BooksView.js
- client/Components/CreatePoll.js
- client/components/Polls.js
- client/components/index.js
- client/routes.js
> feat: added create poll react component

- client/components/Polls.js
> fix: create poll route

- client/components/Polls.js
> fix: create poll path

- client/Components/CreatePoll.js
> fix: changed search into searchResults createPoll react component

- script/seed.js
- server/api/clubs.js
- server/db/models/book/book.js
- server/db/models/index.js
> refactor: db models

- client/components/SinglePoll.js
> style: back to polls link

- client/components/SinglePoll.js
- server/db/models/vote/vote.js
> style: display due date on single poll page

- server/api/clubs.js
> feat: added route /api/club/:clubId/deletemember

- package-lock.json
- server/api/clubs.js
- server/db/models/index.js
- server/db/models/message/message.js
**added back end routes:** 
GET /messages, 
POST /messages,
GET thread /messages/:id, 
POST message to the thread /messages/:id, 
**added security in /clubs routes'**
> feat: added back end messages routes,  added security in /clubs routes

- client/components/AuthForm.js
- client/components/Clubs.js
- client/components/CreateClub.js
- client/components/Sidebar.js
- client/routes.js
- client/store/user.js
- server/auth/index.js
also adds name field to sign up form
> AuthForm, Clubs, & CreateClubs material ui

- client/components/AuthForm.js
- client/components/JoinClub.js
- client/routes.js
- server/api/clubs.js
> style: material ui for invite flow

- client/components/Sidebar.js
- script/seed.js
- server/api/clubs.js
> Invite link

- client/socket.js
- server/socket/index.js
> added debugging info

- client/components/BookSearch/BookList.js
- client/components/BookSearch/BookResults.js
- client/components/BookSearch/DropDownBookOptions.js
- client/components/ClubBooks.js
- client/components/UserBooks.js
- client/store/clubBooks.js
- client/store/user.js
- client/utils.js
- script/seed.js
- server/api/books.js
- server/api/user.js
- server/db/models/clubBook/clubBook.js
- server/db/models/userBook/userBook.js
- Added startTime, endTime to clubs_books and users_books tables. When adding/moving a book, startTime/endTime is populated based on the actions. 
- 'past' book always has endTime set. 'now' book always has startTime set. When moving a 'now' book to 'past' book, startTime of 'past' book is set to be startTime of 'now' book.
- Allow duplicated 'past' books, indicating a book was read multiple times in the past.
- Allow a book to be either 'now' or 'future', but not both.
---
> Drop down books

- client/components/BookSearch/BookList.js
- client/components/BookSearch/Search.js
- client/components/ClubBooks.js
- client/components/Meetings.js
- client/components/Polls.js
- client/components/Sidebar.js
- client/components/SinglePoll.js
- client/index.js
- client/utils.js
- script/seed.js
- server/db/models/poll/poll.js
> F/past polls & meetings

- server/api/clubs.js
- server/db/models/poll/poll.js
> Auto meeting

- client/socket.js
- server/api/books.js
- server/socket/index.js
- Show bookworms emoji, sender's name and club name in notifications
- Render start time and finish time when a book is moved from now to past
---
> Notification

- client/components/BookSearch/BookList.js
- public/style.css
hides scrollbars on firefox and IE
> style: hide scrollbars on firefox and windows

- client/components/NewChart.js
> feat: progress dropdown

- client/components/JoinClub.js
- script/seed-demo.js
> refactor: seed-demo and join club

- client/components/AboutUs.js
> make picutres clickable
